use sqlx::PgPool;
use thiserror::Error;
use uuid::Uuid;
const PERMISSIONS: &[&str] = &["gl:coa:view","gl:coa:configure","gl:journal:view","gl:journal:create","gl:journal:approve","gl:journal:post","gl:period_close:execute","ar:fee_structure:view","ar:fee_structure:configure","ar:fee_collection:collect","ar:fee_collection:view","ar:receipt:cancel","ar:concession:create","ar:scholarship:create","ar:scholarship:approve","ar:refund:create","ar:refund:approve","ap:vendor:create","ap:po:create","ap:po:approve","ap:grn:create","ap:invoice:create","ap:invoice:approve","ap:payment:create","ap:payment:approve","ap:reimbursement:create","ap:reimbursement:approve","treasury:bank_account:view","treasury:bank_account:configure","treasury:reconciliation:perform","treasury:reconciliation:approve","treasury:transfer:create","treasury:transfer:approve","tax:return:view","tax:gst_return:prepare","tax:gst_return:file","tax:tds:deduct","tax:config:configure","budget:budget:view","budget:budget:create","budget:budget:approve","budget:revision:create","budget:encumbrance:view","reports:financial:view","reports:statutory:view","reports:dashboard:view","reports:export","workflow:approval_queue:view","workflow:approval:action","workflow:rule:configure","workflow:exception:handle","admin:user:manage","admin:role:manage","admin:config:manage","admin:audit_log:view","admin:entity:manage"];
#[derive(Debug, Error)] pub enum SeedError { #[error(transparent)] Db(#[from] sqlx::Error) }
pub async fn seed(pool: &PgPool, tenant_id: Uuid) -> Result<(), SeedError> {
 let n: i64 = sqlx::query_scalar("SELECT count(*) FROM roles WHERE tenant_id=$1").bind(tenant_id).fetch_one(pool).await?; if n > 0 { return Ok(()); }
 for code in PERMISSIONS { let mut p=code.split(':'); sqlx::query("INSERT INTO permissions(code,module,resource,action) VALUES($1,$2,$3,$4) ON CONFLICT(code) DO NOTHING").bind(code).bind(p.next().unwrap_or_default()).bind(p.next().unwrap_or_default()).bind(p.next().unwrap_or_default()).execute(pool).await?; }
 for (code,name) in [("trustee","Trustee/Mgmt"),("cfo","CFO"),("finance_controller","Finance Controller"),("accountant","Accountant"),("cashier","Cashier"),("principal","Principal"),("registrar","Registrar"),("hod","HOD"),("faculty","Faculty"),("student","Student/Parent"),("auditor","Auditor"),("procurement","Procurement"),("compliance","Compliance"),("it_admin","IT Admin")] { sqlx::query("INSERT INTO roles(tenant_id,code,name,is_system) VALUES($1,$2,$3,TRUE)").bind(tenant_id).bind(code).bind(name).execute(pool).await?; }
 Ok(())
}
