import { Link } from "react-router-dom";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, CartesianGrid } from "recharts";
import { DashboardHeader, KpiCard, BudgetGauge, ApprovalQueue, ComplianceTimeline, Section } from "./shared";
import { MoneyDisplay } from "../../components/data/MoneyDisplay";

const cash = [{ name: "Apr", value: 42 }, { name: "May", value: 48 }, { name: "Jun", value: 44 }, { name: "Jul", value: 57 }, { name: "Aug", value: 52 }, { name: "Sep", value: 64 }];
const approvals = [{ label: "Purchase Order · PO-2026-184", amount: 185000, age: "2 days", type: "PO" }, { label: "Merit scholarship · SCH-441", amount: 75000, age: "4 days", type: "Scholarship" }, { label: "Fee refund · REF-072", amount: 32000, age: "1 day", type: "Refund" }];
const compliance = [{ name: "GSTR-3B · Campus North", date: "Due 20 Aug 2026", status: "Due soon" as const }, { name: "TDS return · Q1", date: "Due 31 Aug 2026", status: "Due soon" as const }, { name: "GSTR-1 · Campus South", date: "Filed 10 Aug 2026", status: "Filed" as const }, { name: "Professional tax", date: "Due 15 Aug 2026", status: "Overdue" as const }];

export function PrincipalDashboard() { return <div className="space-y-6"><DashboardHeader title="Principal dashboard" subtitle="Institution-wide budget and approvals at a glance." /><div className="grid gap-4 md:grid-cols-4"><KpiCard title="Budget utilized" value="68%" trend="4.2%" /><KpiCard title="Pending approvals" value="12" trend="3" positive={false} /><KpiCard title="Scholarships disbursed" amount={12400000} trend="12%" /><KpiCard title="Pending verification" value="28" trend="6" positive={false} /></div><div className="grid gap-6 lg:grid-cols-2"><Section title="Department expense vs allocation"><ResponsiveContainer width="100%" height={250}><BarChart data={[{ n: "Science", expense: 72, allocation: 90 }, { n: "Arts", expense: 48, allocation: 60 }, { n: "Admin", expense: 81, allocation: 85 }, { n: "Engineering", expense: 66, allocation: 80 }]}><XAxis dataKey="n" /><YAxis /><Tooltip /><Bar dataKey="allocation" fill="#c7d2fe" /><Bar dataKey="expense" fill="#6366f1" /></BarChart></ResponsiveContainer></Section><ApprovalQueue items={approvals} /></div></div>; }

export function AccountantDashboard() { return <div className="space-y-6"><DashboardHeader title="Accountant dashboard" subtitle="Today's operational finance work." /><div className="grid gap-4 md:grid-cols-4"><KpiCard title="Today's collections" amount={842500} trend="8%" /><KpiCard title="Target achievement" value="84%" trend="₹1.0L target" /><KpiCard title="Vendor invoices" value="19" trend="4 PO gaps" positive={false} /><KpiCard title="Journals awaiting posting" value="7" trend="2 new" positive={false} /></div><div className="grid gap-6 lg:grid-cols-2"><KpiCard title="Unreconciled bank entries" value="34" trend="Reconcile now" positive={false} href="/treasury/reconciliation" /><Section title="PO-to-invoice gaps"><ul className="space-y-3 text-sm"><li className="flex justify-between"><span>PO-2026-184 · IT equipment</span><span className="font-semibold text-amber-600">₹18,500 gap</span></li><li className="flex justify-between"><span>PO-2026-176 · Lab supplies</span><span className="font-semibold text-amber-600">₹7,200 gap</span></li></ul></Section></div></div>; }

export function HodDashboard() { return <div className="space-y-6"><DashboardHeader title="Department dashboard" subtitle="Department budget, commitments and grants." /><div className="grid gap-4 md:grid-cols-3"><KpiCard title="Budget remaining" amount={1840000} trend="68% utilized" /><KpiCard title="Encumbrance" amount={620000} trend="Within limit" /><KpiCard title="Grant utilization" value="72%" trend="₹8.4L of ₹11.7L" /></div><div className="grid gap-6 lg:grid-cols-2"><BudgetGauge label="Department budget utilization" value={68} detail="₹18.4L available after encumbrance" /><Section title="Pending purchase orders"><ul className="divide-y text-sm">{["PO-2026-184 · Computer lab", "PO-2026-179 · Research consumables", "PO-2026-173 · Fieldwork travel"].map(x => <li className="flex justify-between py-3" key={x}><span>{x}</span><Link className="text-primary" to="/ap/purchase-orders">Review →</Link></li>)}</ul></Section></div></div>; }

export function StudentDashboard() { return <div className="space-y-6"><DashboardHeader title="My fees" subtitle="Your fee account, scholarships and receipts." /><div className="grid gap-4 md:grid-cols-3"><CardFee /><KpiCard title="Next installment" amount={45000} trend="Due 15 Sep 2026" positive={false} /><KpiCard title="Scholarship status" value="Sanctioned" trend="Step 3 of 5" /></div><Section title="Recent payments"><div className="divide-y text-sm">{["05 Aug 2026", "12 Jul 2026", "08 Jun 2026", "11 Apr 2026", "04 Apr 2026"].map((d, i) => <div className="flex justify-between py-3" key={d}><span>Receipt RCP-26-0{i + 81} · {d}</span><MoneyDisplay amount={[4500000, 3000000, 2500000, 1800000, 1200000][i]} /><span className="text-emerald-600">Paid</span></div>)}</div></Section></div>; }
function CardFee() { return <KpiCard title="Outstanding fee balance" amount={4500000} trend="Due" positive={false} />; }

export function AuditorDashboard() { return <div className="space-y-6"><DashboardHeader title="Audit workspace" subtitle="Exceptions and control health across the institution." /><div className="grid gap-4 md:grid-cols-4"><KpiCard title="Exception flags" value="11" trend="3 high priority" positive={false} /><KpiCard title="Unreconciled accounts" value="6" trend="2 new" positive={false} /><KpiCard title="Trial balance variance" amount={12500} trend="Investigate" positive={false} /><KpiCard title="Sample completion" value="64%" trend="Audit plan" /></div><div className="grid gap-6 lg:grid-cols-2"><Section title="Exception flags"><ul className="space-y-3 text-sm"><li className="rounded-lg bg-rose-50 p-3"><b>Duplicate payment</b><br />PAY-2026-091 · ₹2,40,000 · Vendor duplicate</li><li className="rounded-lg bg-amber-50 p-3"><b>Stale receivable</b><br />42 student accounts over 180 days</li></ul></Section><Section title="Quick links"><div className="grid grid-cols-2 gap-3 text-sm">{[["GL ledger", "/gl/journals"], ["Audit log", "/settings"], ["GST reports", "/tax/gst"], ["TDS register", "/tax/tds"]].map(([label, href]) => <Link className="rounded-lg border p-3 font-medium text-primary hover:bg-indigo-50" to={href} key={href}>{label} →</Link>)}</div></Section></div></div>; }

export function GenericDashboard() { return <div className="space-y-6"><DashboardHeader title="Institution dashboard" subtitle="Your permitted finance and administration workspace." /><div className="grid gap-4 md:grid-cols-3"><KpiCard title="Cash position" amount={4523000} /><KpiCard title="Open tasks" value="8" /><KpiCard title="Collection rate" value="91%" /></div><ComplianceTimeline items={compliance} /></div>; }

export default function CfoDashboard() { return <div className="space-y-6"><DashboardHeader title="CFO dashboard" subtitle="Cash, performance and compliance across all campuses." /><div className="grid gap-4 md:grid-cols-4"><KpiCard title="Revenue YTD" amount={86400000} trend="12.4%" /><KpiCard title="Expenditure YTD" amount={57200000} trend="6.1%" positive={false} /><KpiCard title="Net surplus" amount={29200000} trend="18.2%" /><KpiCard title="Fee collection rate" value="91.4%" trend="Target 90%" /></div><div className="grid gap-6 lg:grid-cols-3"><Section title="Cash flow · last 6 months"><ResponsiveContainer width="100%" height={240}><LineChart data={cash}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis tickFormatter={v => `₹${v}L`} /><Tooltip /><Line type="monotone" dataKey="value" stroke="#6366f1" strokeWidth={3} /></LineChart></ResponsiveContainer></Section><div className="space-y-4"><KpiCard title="Bank balance" amount={23840000} /><KpiCard title="Pending approvals" value="14" trend="Review queue" positive={false} /></div><div className="space-y-4"><KpiCard title="Unreconciled items" value="34" trend="Needs attention" positive={false} /><BudgetGauge label="Budget utilization" value={68} detail="Across all funds" /></div></div><ComplianceTimeline items={compliance} /></div>; }
